version: '3.7'

services:     
  mariadb:
    container_name: 13_web-mariadb
    hostname: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: webdb
      MARIADB_USER: webdb
      MARIADB_PASSWORD: password
    ports:
      - "0.0.0.0:5013:3306"      
  web:
    container_name: 13_web-app-calculator
    hostname: app
    build: Calculator/
    ports:
      - "0.0.0.0:5013:5013"
